# Generated by Django 4.1.2 on 2022-11-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_claimprofile_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimprofile',
            name='connection',
            field=models.CharField(choices=[('S', 'Staff'), ('B', 'Board member'), ('V', 'Volunteer'), ('C', 'Consultant')], default='Staff', max_length=9, verbose_name='How are you connected to the organization?'),
        ),
    ]
