# Generated by Django 4.1.2 on 2022-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ngo_compliance_doc_alter_ngo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimprofile',
            name='connection',
            field=models.CharField(choices=[('S', 'S'), ('B', 'B'), ('V', 'V'), ('C', 'C')], default='S', max_length=200, verbose_name='How are you connected to the organization?'),
        ),
    ]
