# Generated by Django 4.1.2 on 2022-11-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_claimprofile_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='principal_officer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
